"""
Page routes and HTML view controllers for the Satellite Telemetry Web Application.
"""
import os
import json
import time
from datetime import datetime, timezone
from fastapi import APIRouter, Request, Form, Depends, HTTPException, status
from fastapi.responses import HTMLResponse, RedirectResponse, FileResponse
from fastapi.templating import Jinja2Templates

from config import (
    TOTAL_TEAMS, MASTER_SECRET, EVENT_JOIN_CODE, ADMIN_PASSWORD,
    TEAMS_DATA_DIR, ANSWERS_DIR, CHALLENGE_POINTS, MISSION_NAME
)
from models import get_db_connection
from app.auth import hash_password, verify_password, verify_admin_password

templates = Jinja2Templates(directory=os.path.join(os.path.dirname(__file__), "templates"))
pages_router = APIRouter()

def get_session_team(request: Request):
    team_id = request.session.get("team_id")
    if not team_id:
        return None
    conn = get_db_connection()
    cur = conn.cursor()
    cur.execute("SELECT * FROM teams WHERE id = ?", (team_id,))
    team = cur.fetchone()
    conn.close()
    return team

def is_admin(request: Request) -> bool:
    return bool(request.session.get("is_admin"))

# -----------------------------------------------------------------------------
# AUTHENTICATION PAGES
# -----------------------------------------------------------------------------
@pages_router.get("/", response_class=HTMLResponse)
async def index_page(request: Request):
    team = get_session_team(request)
    if team:
        return RedirectResponse(url="/dashboard", status_code=302)
    return RedirectResponse(url="/login", status_code=302)

@pages_router.get("/login", response_class=HTMLResponse)
async def login_page(request: Request):
    team = get_session_team(request)
    if team:
        return RedirectResponse(url="/dashboard", status_code=302)
    return templates.TemplateResponse("login.html", {"request": request, "error": None})

@pages_router.post("/login", response_class=HTMLResponse)
async def login_submit(request: Request, team_name: str = Form(...), password: str = Form(...)):
    conn = get_db_connection()
    cur = conn.cursor()
    cur.execute("SELECT * FROM teams WHERE name = ?", (team_name.strip(),))
    team = cur.fetchone()
    conn.close()
    
    if not team or not verify_password(team["pw_hash"], password):
        return templates.TemplateResponse("login.html", {"request": request, "error": "Invalid team name or password."})
        
    request.session["team_id"] = team["id"]
    request.session["team_name"] = team["name"]
    return RedirectResponse(url="/dashboard", status_code=302)

@pages_router.get("/register", response_class=HTMLResponse)
async def register_page(request: Request):
    return templates.TemplateResponse("register.html", {"request": request, "error": None})

@pages_router.post("/register", response_class=HTMLResponse)
async def register_submit(
    request: Request,
    team_id: int = Form(...),
    team_name: str = Form(...),
    password: str = Form(...),
    join_code: str = Form(...)
):
    if join_code.strip() != EVENT_JOIN_CODE:
        return templates.TemplateResponse("register.html", {"request": request, "error": "Invalid Event Join Code. Check your briefing sheet."})
        
    if team_id < 1 or team_id > TOTAL_TEAMS:
        return templates.TemplateResponse("register.html", {"request": request, "error": f"Team ID must be between 1 and {TOTAL_TEAMS}."})
        
    # Read generated metadata
    answers_file = os.path.join(ANSWERS_DIR, "master_answers.json")
    if not os.path.exists(answers_file):
        return templates.TemplateResponse("register.html", {"request": request, "error": "Competition data not yet generated by flight director."})
        
    with open(answers_file, "r", encoding="utf-8") as f:
        master_answers = json.load(f)
        
    team_data = master_answers.get(str(team_id))
    if not team_data:
        return templates.TemplateResponse("register.html", {"request": request, "error": f"Team {team_id} not found in master configuration."})
        
    conn = get_db_connection()
    cur = conn.cursor()
    
    cur.execute("SELECT * FROM teams WHERE id = ? OR name = ?", (team_id, team_name.strip()))
    if cur.fetchone():
        conn.close()
        return templates.TemplateResponse("register.html", {"request": request, "error": f"Team {team_id} or Team Name '{team_name}' is already registered."})
        
    pw_hash = hash_password(password)
    cur.execute("""
    INSERT INTO teams (id, name, pw_hash, seed, credits, api_token, launch_auth_code, created_at)
    VALUES (?, ?, ?, ?, 12, ?, ?, ?)
    """, (team_id, team_name.strip(), pw_hash, team_data["seed"], team_data["api_token"], team_data["launch_auth_code"], datetime.now(timezone.utc).isoformat()))
    
    conn.commit()
    conn.close()
    
    request.session["team_id"] = team_id
    request.session["team_name"] = team_name.strip()
    return RedirectResponse(url="/dashboard", status_code=302)

@pages_router.get("/logout")
async def logout(request: Request):
    request.session.clear()
    return RedirectResponse(url="/login", status_code=302)

# -----------------------------------------------------------------------------
# DASHBOARD & CHALLENGES
# -----------------------------------------------------------------------------
@pages_router.get("/dashboard", response_class=HTMLResponse)
async def dashboard_page(request: Request):
    team = get_session_team(request)
    if not team:
        return RedirectResponse(url="/login", status_code=302)
        
    conn = get_db_connection()
    cur = conn.cursor()
    
    # Fetch team credits
    cur.execute("SELECT credits FROM teams WHERE id = ?", (team["id"],))
    credits = cur.fetchone()["credits"]
    
    # Fetch all challenges
    cur.execute("SELECT * FROM challenges WHERE round_id IN (2, 4) ORDER BY order_num ASC")
    challenges = [dict(c) for c in cur.fetchall()]
    
    # Fetch team solves
    cur.execute("SELECT * FROM submissions WHERE team_id = ? AND correct = 1", (team["id"],))
    solves = {s["challenge_id"]: dict(s) for s in cur.fetchall()}
    
    # Fetch team flags
    cur.execute("SELECT * FROM flags WHERE team_id = ?", (team["id"],))
    flags = {f["phase"]: f["flag"] for f in cur.fetchall()}
    
    # App states
    cur.execute("SELECT * FROM app_state")
    app_state = {r["key"]: r["value"] for r in cur.fetchall()}
    
    # Fetch Round Statuses for all 4 Rounds
    cur.execute("SELECT round_id, status, score, unlocked_at, submitted_at FROM round_status WHERE team_id = ?", (team["id"],))
    raw_round_statuses = {r["round_id"]: dict(r) for r in cur.fetchall()}
    
    conn.close()
    
    # Round 4 retains only its live finale. Round 2 owns the telemetry investigation.
    phases = {
        "FINALE": {"title": "Phase 4: Live Contingency Finale", "desc": "Real-time state machine anomaly recovery using the flight runbook.", "challenges": []}
    }

    for ch in challenges:
        ch["is_solved"] = (ch["id"] in solves)
        ch["points_awarded"] = solves[ch["id"]]["points_awarded"] if ch["is_solved"] else 0
        if ch["round_id"] == 4 and ch["phase"] in phases:
            phases[ch["phase"]]["challenges"].append(ch)
            
    round4_score = sum(s["points_awarded"] for s in solves.values() if any(ch["id"] == s["challenge_id"] and ch["round_id"] == 4 for ch in challenges))
    
    # Establish defaults for each round
    rounds_summary = {}
    for rid in [1, 2, 3, 4]:
        st = raw_round_statuses.get(rid, {"status": "locked", "score": 0, "unlocked_at": None, "submitted_at": None})
        rounds_summary[rid] = st
        
    # Round 1 default is active if not set
    if rounds_summary[1]["status"] == "locked":
        rounds_summary[1]["status"] = "active"
        
    # Check unlock progression with overrides
    if (rounds_summary[1]["status"] == "submitted" or app_state.get("round2_active") == "true") and rounds_summary[2]["status"] == "locked":
        rounds_summary[2]["status"] = "active"
        
    if (rounds_summary[2]["status"] == "submitted" or app_state.get("round3_active") == "true") and rounds_summary[3]["status"] == "locked":
        rounds_summary[3]["status"] = "active"
        
    if (rounds_summary[3]["status"] == "submitted" or app_state.get("round4_active") == "true") and rounds_summary[4]["status"] == "locked":
        rounds_summary[4]["status"] = "active"
        
    rounds_summary[4]["score"] = round4_score
    if round4_score > 0 and rounds_summary[4]["status"] != "submitted":
        rounds_summary[4]["status"] = "active"

    # CRITICAL: Strip Round 3 raw score so it CANNOT be leaked to team client/DOM
    rounds_summary[3].pop("score", None)
    
    # Total visible score aggregates Rounds 1 + 2 + 4 only
    r1_score = rounds_summary[1]["score"] if rounds_summary[1]["status"] == "submitted" else 0
    r2_score = rounds_summary[2]["score"] if rounds_summary[2]["status"] == "submitted" else 0
    total_score = r1_score + r2_score + round4_score
    
    return templates.TemplateResponse("dashboard.html", {
        "request": request,
        "team": team,
        "credits": credits,
        "phases": phases,
        "flags": flags,
        "rounds_summary": rounds_summary,
        "r1_score": r1_score,
        "r2_score": r2_score,
        "r4_score": round4_score,
        "total_score": total_score,
        "app_state": app_state,
        "mission_name": MISSION_NAME
    })

@pages_router.get("/challenge/{challenge_id}", response_class=HTMLResponse)
async def challenge_detail_page(request: Request, challenge_id: str):
    team = get_session_team(request)
    if not team:
        return RedirectResponse(url="/login", status_code=302)
        
    conn = get_db_connection()
    cur = conn.cursor()
    
    cur.execute("SELECT * FROM challenges WHERE id = ?", (challenge_id.upper(),))
    ch = cur.fetchone()
    if not ch:
        conn.close()
        raise HTTPException(status_code=404, detail="Challenge not found.")
        
    if ch["round_id"] == 2 and ch["phase"] in ("PHASE_2", "PHASE_3"):
        required_phase = "PHASE_1" if ch["phase"] == "PHASE_2" else "PHASE_2"
        cur.execute("SELECT 1 FROM flags WHERE team_id = ? AND phase = ?", (team["id"], required_phase))
        if not cur.fetchone():
            conn.close()
            return RedirectResponse(url="/round2", status_code=302)

    cur.execute("SELECT * FROM submissions WHERE team_id = ? AND challenge_id = ? ORDER BY ts_utc_ms DESC", (team["id"], ch["id"]))
    submissions = [dict(s) for s in cur.fetchall()]
    
    is_solved = any(s["correct"] == 1 for s in submissions)
    solved_sub = next((s for s in submissions if s["correct"] == 1), None)
    
    # Calculate cooldown
    wrong_count = len(submissions) if not is_solved else 0
    in_cooldown = False
    cooldown_rem = 0
    if wrong_count >= 5 and not is_solved:
        last_ts = submissions[0]["ts_utc_ms"]
        elapsed = (int(time.time() * 1000) - last_ts) / 1000.0
        if elapsed < 600:
            in_cooldown = True
            cooldown_rem = int(600 - elapsed)
            
    conn.close()
    
    return templates.TemplateResponse("challenge.html", {
        "request": request,
        "team": team,
        "challenge": dict(ch),
        "submissions": submissions,
        "is_solved": is_solved,
        "solved_sub": solved_sub,
        "in_cooldown": in_cooldown,
        "cooldown_rem": cooldown_rem
    })

# -----------------------------------------------------------------------------
# PACKAGES & DOWNLOADS
# -----------------------------------------------------------------------------
@pages_router.get("/packages", response_class=HTMLResponse)
async def packages_page(request: Request):
    team = get_session_team(request)
    if not team:
        return RedirectResponse(url="/login", status_code=302)
        
    conn = get_db_connection()
    cur = conn.cursor()
    cur.execute("SELECT * FROM flags WHERE team_id = ?", (team["id"],))
    flags = {f["phase"]: f["flag"] for f in cur.fetchall()}
    conn.close()
    
    return templates.TemplateResponse("packages.html", {
        "request": request,
        "team": team,
        "flags": flags
    })

@pages_router.get("/download/package/{team_id}/{phase_filename}")
async def download_phase_package(request: Request, team_id: int, phase_filename: str):
    team = get_session_team(request)
    # Ensure team only downloads their own package unless admin
    if not team and not is_admin(request):
        raise HTTPException(status_code=401, detail="Authentication required.")
    if team and team["id"] != team_id and not is_admin(request):
        raise HTTPException(status_code=403, detail="Access denied to another team's package.")
        
    # Evidence packages are staged by Round 2 phase.
    if phase_filename.endswith("_phase1.zip"):
        conn = get_db_connection()
        cur = conn.cursor()
        cur.execute("SELECT 1 FROM round_status WHERE team_id = ? AND round_id = 1 AND status = 'submitted'", (team_id,))
        unlocked = cur.fetchone()
        conn.close()
        if not unlocked and not is_admin(request):
            raise HTTPException(status_code=403, detail="Round 2 is sealed until Round 1 is verified.")
    elif phase_filename.endswith("_phase2.zip") or phase_filename.endswith("_phase3.zip"):
        conn = get_db_connection()
        cur = conn.cursor()
        required_phase = "PHASE_1" if phase_filename.endswith("_phase2.zip") else "PHASE_2"
        cur.execute("SELECT 1 FROM flags WHERE team_id = ? AND phase = ?", (team_id, required_phase))
        unlocked = cur.fetchone()
        conn.close()
        if not unlocked and not is_admin(request):
            raise HTTPException(status_code=403, detail="This telemetry package is still sealed.")

    pkg_path = os.path.join(TEAMS_DATA_DIR, f"team_{team_id:02d}", "packages", phase_filename)
    if not os.path.exists(pkg_path):
        raise HTTPException(status_code=404, detail="Package file not found.")
        
    return FileResponse(pkg_path, filename=phase_filename, media_type="application/zip")

# -----------------------------------------------------------------------------
# SCOREBOARD & CONSOLE & DOCUMENTS
# -----------------------------------------------------------------------------
@pages_router.get("/scoreboard", response_class=HTMLResponse)
async def scoreboard_page(request: Request):
    return templates.TemplateResponse("scoreboard.html", {"request": request})

@pages_router.get("/console", response_class=HTMLResponse)
async def console_page(request: Request):
    team = get_session_team(request)
    if not team:
        return RedirectResponse(url="/login", status_code=302)
    return templates.TemplateResponse("console.html", {"request": request, "team": team})

@pages_router.get("/documents", response_class=HTMLResponse)
async def documents_page(request: Request):
    team = get_session_team(request)
    return templates.TemplateResponse("documents.html", {"request": request, "team": team})

@pages_router.get("/round1-sheet/{team_id}", response_class=HTMLResponse)
async def round1_sheet_view(request: Request, team_id: int):
    # Printable sheet for Round 1
    answers_file = os.path.join(ANSWERS_DIR, "master_answers.json")
    with open(answers_file, "r", encoding="utf-8") as f:
        master_answers = json.load(f)
    t_data = master_answers.get(str(team_id))
    if not t_data:
        raise HTTPException(status_code=404, detail="Team data not found.")
        
    return templates.TemplateResponse("round1_sheet.html", {
        "request": request,
        "team_id": team_id,
        "data": t_data
    })

# -----------------------------------------------------------------------------
# ADMIN CONTROL PANEL
# -----------------------------------------------------------------------------
@pages_router.get("/admin", response_class=HTMLResponse)
async def admin_page(request: Request):
    if not is_admin(request):
        return templates.TemplateResponse("admin_login.html", {"request": request, "error": None})
        
    conn = get_db_connection()
    cur = conn.cursor()
    cur.execute("SELECT * FROM teams ORDER BY id ASC")
    teams = [dict(t) for t in cur.fetchall()]
    
    cur.execute("SELECT * FROM app_state")
    app_state = {r["key"]: r["value"] for r in cur.fetchall()}
    
    # 1. Fetch round statuses across all 4 rounds
    cur.execute("SELECT * FROM round_status")
    all_round_statuses = cur.fetchall()
    # Map: (team_id, round_id) -> row dict
    team_rounds = {}
    for rs in all_round_statuses:
        team_rounds[(rs["team_id"], rs["round_id"])] = dict(rs)
        
    # 2. Fetch Round 3 Game Sessions (secret scores)
    cur.execute("SELECT * FROM game_sessions ORDER BY id DESC")
    game_sessions = [dict(g) for g in cur.fetchall()]
    
    # 3. Fetch Round 4 Solves per team
    cur.execute("SELECT team_id, COUNT(*) as solves, SUM(points_awarded) as r4_pts FROM submissions WHERE correct = 1 GROUP BY team_id")
    r4_solves_map = {row["team_id"]: (row["solves"], row["r4_pts"] or 0) for row in cur.fetchall()}
    
    # Compile Master Team Overview
    team_overview = []
    for tm in teams:
        tid = tm["id"]
        r1_info = team_rounds.get((tid, 1), {"status": "active", "score": 0, "submitted_at": None})
        r2_info = team_rounds.get((tid, 2), {"status": "locked", "score": 0, "submitted_at": None})
        r3_info = team_rounds.get((tid, 3), {"status": "locked", "score": 0, "submitted_at": None})
        r4_solves, r4_pts = r4_solves_map.get(tid, (0, 0))
        
        r1_score = r1_info["score"] if r1_info["status"] == "submitted" else 0
        r2_score = r2_info["score"] if r2_info["status"] == "submitted" else 0
        r3_score = r3_info["score"] if r3_info["status"] == "submitted" else 0
        
        grand_total = r1_score + r2_score + r3_score + r4_pts
        public_total = r1_score + r2_score + r4_pts
        
        team_overview.append({
            "team": tm,
            "r1": r1_info,
            "r2": r2_info,
            "r3": r3_info,
            "r4_solves": r4_solves,
            "r4_pts": r4_pts,
            "grand_total": grand_total,
            "public_total": public_total
        })
        
    # Sort teams by Grand Total descending
    team_overview.sort(key=lambda x: -x["grand_total"])

    # 4. Fetch Security & Timing Events
    cur.execute("SELECT * FROM events ORDER BY ts_utc_ms DESC LIMIT 40")
    recent_events = [dict(e) for e in cur.fetchall()]
    
    # 5. Fetch Recent Submissions
    cur.execute("SELECT * FROM submissions ORDER BY ts_utc_ms DESC LIMIT 30")
    recent_subs = [dict(s) for s in cur.fetchall()]
    
    conn.close()
    
    return templates.TemplateResponse("admin.html", {
        "request": request,
        "teams": teams,
        "team_overview": team_overview,
        "app_state": app_state,
        "recent_subs": recent_subs,
        "game_sessions": game_sessions,
        "recent_events": recent_events
    })

@pages_router.post("/admin/login", response_class=HTMLResponse)
async def admin_login_submit(request: Request, password: str = Form(...)):
    if verify_admin_password(password):
        request.session["is_admin"] = True
        return RedirectResponse(url="/admin", status_code=302)
    return templates.TemplateResponse("admin_login.html", {"request": request, "error": "Invalid admin credentials."})

@pages_router.post("/admin/action")
async def admin_action(request: Request, action: str = Form(...), team_id: int = Form(None), val: str = Form(None)):
    if not is_admin(request):
        raise HTTPException(status_code=401, detail="Admin authorization required.")
        
    conn = get_db_connection()
    cur = conn.cursor()
    
    if action == "freeze_scoreboard":
        cur.execute("UPDATE app_state SET value = 'true' WHERE key = 'scoreboard_frozen'")
    elif action == "unfreeze_scoreboard":
        cur.execute("UPDATE app_state SET value = 'false' WHERE key = 'scoreboard_frozen'")
    elif action == "release_errata":
        cur.execute("UPDATE app_state SET value = 'true' WHERE key = 'errata_released'")
    elif action == "start_finale":
        cur.execute("UPDATE app_state SET value = 'true' WHERE key = 'finale_started'")
    elif action == "toggle_round" and val:
        # Toggle round active state (e.g. round2_active)
        cur.execute("SELECT value FROM app_state WHERE key = ?", (val,))
        row = cur.fetchone()
        new_val = "false" if (row and row["value"] == "true") else "true"
        cur.execute("INSERT OR REPLACE INTO app_state (key, value) VALUES (?, ?)", (val, new_val))
    elif action == "adjust_credits" and team_id is not None and val:
        credits_delta = int(val)
        cur.execute("UPDATE teams SET credits = credits + ? WHERE id = ?", (credits_delta, team_id))
    elif action == "reset_cooldown" and team_id is not None:
        cur.execute("DELETE FROM submissions WHERE team_id = ? AND correct = 0", (team_id,))
    elif action == "unlock_round" and team_id is not None and val:
        round_to_unlock = int(val)
        cur.execute("""
        INSERT OR REPLACE INTO round_status (team_id, round_id, status, score, unlocked_at)
        VALUES (?, ?, 'active', 0, ?)
        """, (team_id, round_to_unlock, datetime.now(timezone.utc).isoformat()))
        
    conn.commit()
    conn.close()
    return RedirectResponse(url="/admin", status_code=302)
